apiVersion: v1
kind: Service
metadata:
  name: mi-microservicio
  namespace: vallegrande
spec:
  selector:
    app: mi-microservicio
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
